apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp
spec:
  replicas: 3  # Number of pod replicas
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: saba2002/nodeapp:latest # Replace with your image
        ports:
        - containerPort: 3000 # Port the Node.js app listens on
