service:
    name: ownappservice
    identifier: ownappservice
    serviceDefinition:
        type: Kubernetes
        spec:
            manifests:
                - manifest:
                    identifier: nodeapp
                    type: K8sManifest
                    spec:
                      store:
                        type: Github
                        spec:
                            connectorRef: ownappgitconnector
                            gitFetchType: Branch
                            paths:
                                - deployment.yaml
                                - service.yaml
                            repoName: nodeapp-1
                            branch: master
                        skipResourceVersioning: false
                        enableDeclarativeRollback: false
